import os
from jose.constants import ALGORITHMS

JWT_ACCESS_TOKEN_EXP = os.getenv("JWT_ACCESS_TOKEN_EXP", 36000 * 2)
JWT_ACCESS_TOKEN_KEY = os.getenv("JWT_ACCESS_TOKEN_KEY", "key")
JWT_ACCESS_TOKEN_ALG = os.getenv("JWT_ACCESS_TOKEN_ALG", ALGORITHMS.HS256)

JWT_REFRESH_TOKEN_EXP = os.getenv("JWT_REFRESH_TOKEN_EXP", 36000 * 2)
JWT_REFRESH_TOKEN_KEY = os.getenv("JWT_REFRESH_TOKEN_KEY", "key")
JWT_REFRESH_TOKEN_ALG = os.getenv("JWT_REFRESH_TOKEN_ALG", ALGORITHMS.HS256)

SMTP_EMAIL_ADDRESS = os.getenv("SMTP_EMAIL_ADDRESS", "abdullahdeliogullari@gmail.com")
SMTP_EMAIL_APP_PASSWORD = os.getenv("SMTP_EMAIL_APP_PASSWORD", "smwrjwrgabjoneox")
